version: '3'
services:
  todoback:
    image: todobackend
    # restart: always
    ports:
      - 3001:3001
  todofront:
    image: todofrontend
    # restart: always
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
  todotests:
    image: todotests
    restart: always
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todoback
      - todofront

# Agradeço a ajuda dos meus amigos Antonio Nunes, Arthur Teixeira e Valdênio Martinho